Rename Dataset to Table
ga4gh-discovery/data-connect pull request #21
Opened 2019-09-19 14:26 UTC by mfiume

* rename dataset to table
* rename schema to data_model
* rename objects to data
* other renaming
* introduce new /data endpoint

2019-09-19 14:45 UTC, mcupak approved these changes

2019-09-30 15:57 UTC, davidlougheed commented
Any thoughts on my concerns in #18? This still applies with the rename; and the README mentions `/datasets/{id}` instead of `/dataset/{id}` in some places as well.

2019-10-21 03:30 UTC, mcupak requested changes
Needs rebasing.

2019-10-30 18:46 UTC, patmagee commented
@mfiume @mcupak FYI the README.md needs to be updated. All of the documentation is outdated

2019-10-30 19:22 UTC, jfuerth approved these changes
Looks good. Just a few suggestions on wording.

We should also
* update DATASET.md (rename to tables.md and edit content)
* update content of README.md to refer to "Tables" rather than "Datasets" and "Data Model" rather than "Schema"

Doesn't need to block this, but should be done soon after merging.

2019-10-30 19:22 UTC, jfuerth commented on spec/search-api.yaml
> +      description: Returns the Table identified by name.
suggest: "Returns information about the Table identified by table_name"

2019-10-30 19:22 UTC, jfuerth commented on spec/search-api.yaml
> +      operationId: data
maybe get_table_data?

2019-10-30 19:22 UTC, jfuerth commented on spec/search-api.yaml
> +      responses:
Add a 200 success response that returns TableData?

2019-10-30 19:22 UTC, jfuerth commented on spec/search-api.yaml
>        responses:
Add a 200 success response that returns TableData?

2019-10-30 19:22 UTC, jfuerth commented on spec/search-api.yaml
> +          description: Optional description of the Table
Suggest: Human-readable description of the Table (Optional)

2019-10-30 20:14 UTC, patmagee commented
@mcupak #24 should be merved over this PR. I addressed the issues outlined by @jfuerth and updated some of the documentation

2019-11-18 16:43 UTC, merged